### ISSUE TITLE
Support .editorconfig

### ISSUE THREAD

**Issue by AAverin** [ScaCap/action-ktlint#22]
It should be possible to read files from repository inside Docker container of the action (https://github.community/t/how-can-i-access-the-current-repo-context-and-files-from-a-docker-container-action/17711).

It should allow to read .editorconfig file, used in the project from the root project folder or provided path to make sure that rules are the same for local ktlint runs and github actions lint checks.

**Comment by ilya40umov** [comment]
As far as I understand repo's `.editorconfig` is actually already utilized by the action, as the code must anyway first be checked out along with all other committed files (like `.editorconfig`) and only then the ktlint will be run by the action: https://github.com/ScaCap/action-ktlint/blob/master/entrypoint.sh#L41

Initially, I also attributed the difference between ktlint results on my local machine and the ones coming from GH action to the action ignoring my `.editorconfig` settings, but then it turned out to be due to a difference between ktlint versions: the action is using "latest" by default, while [ktlint gradle plugin](https://github.com/JLLeitschuh/ktlint-gradle) is using an older version of ktlint.

P.S. I guess adding an input parameter for controlling the location of the `.editorconfig` file is still something the action should add.

**Comment by ghaiszaher** [comment]
`.editorconfig` is already considered by the action. @AAverin can you provide an example where this didn't work?

**Comment by AAverin** [comment]
As this was almost a year ago, I am very far out of context on this issue. We have opted out of using ktlint in actions for now, so I don't have any actionable example.
If anyone also experiences this issue, please reopen and provide an example. I will do so if I will be exploring ktlint in actions again.
